"""Add splited field to Video model

Revision ID: 1837821a6601
Revises: 1a1016c6692a
Create Date: 2025-01-13 00:51:38.500810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1837821a6601'
down_revision = '1a1016c6692a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_campaigns', schema=None) as batch_op:
        batch_op.drop_index('facebook_campaign_id')

    op.drop_table('facebook_campaigns')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facebook_campaigns',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('facebook_campaign_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('objective', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('created_time', mysql.DATETIME(), nullable=True),
    sa.Column('updated_time', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('facebook_account_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['facebook_account_id'], ['facebook_account.id'], name='facebook_campaigns_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='facebook_campaigns_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('facebook_campaigns', schema=None) as batch_op:
        batch_op.create_index('facebook_campaign_id', ['facebook_campaign_id'], unique=True)

    # ### end Alembic commands ###
