"""Add splited field to Video model

Revision ID: 1a1016c6692a
Revises: 3f123863abfd
Create Date: 2025-01-12 22:33:40.611066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1016c6692a'
down_revision = '3f123863abfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_ad_accounts', schema=None) as batch_op:
        batch_op.drop_constraint('facebook_ad_accounts_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'facebook_account', ['facebook_account_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_ad_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('facebook_ad_accounts_ibfk_1', 'facebook_account', ['facebook_account_id'], ['id'])

    # ### end Alembic commands ###
