"""Add video_id column to StackPost

Revision ID: 21ed981625e3
Revises: 3380771ac678
Create Date: 2025-01-06 22:55:26.075122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ed981625e3'
down_revision = '3380771ac678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stack_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted_video_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stack_post', schema=None) as batch_op:
        batch_op.drop_column('posted_video_id')

    # ### end Alembic commands ###
