"""Fix relationship between StackPost and Page

Revision ID: 3380771ac678
Revises: d2fd176cc311
Create Date: 2025-01-05 22:35:59.392405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3380771ac678'
down_revision = 'd2fd176cc311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stack_post', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'page', ['page_id'], ['page_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stack_post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
