"""change user facebook id

Revision ID: 35badcd8deb5
Revises: 82911264abbc
Create Date: 2025-01-12 10:39:36.017503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35badcd8deb5'
down_revision = '82911264abbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_user_id', sa.String(length=255), nullable=True))
        batch_op.drop_index('email')
        batch_op.create_unique_constraint(None, ['facebook_user_id'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('email', ['email'], unique=True)
        batch_op.drop_column('facebook_user_id')

    # ### end Alembic commands ###
