"""Add special_ad_categories to FacebookCampaign

Revision ID: 3c600a886d2e
Revises: 1837821a6601
Create Date: 2025-01-13 09:38:25.232062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c600a886d2e'
down_revision = '1837821a6601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special_ad_categories', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_campaign', schema=None) as batch_op:
        batch_op.drop_column('special_ad_categories')

    # ### end Alembic commands ###
