"""Add splited field to Video model

Revision ID: 3f123863abfd
Revises: 6b18ace0fb75
Create Date: 2025-01-12 22:18:08.508361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f123863abfd'
down_revision = '6b18ace0fb75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_ad_accounts', schema=None) as batch_op:
        batch_op.alter_column('facebook_account_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_ad_accounts', schema=None) as batch_op:
        batch_op.alter_column('facebook_account_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
