"""Add splited field to Video model

Revision ID: 46573d064bf4
Revises: f54a480ef00c
Create Date: 2025-01-21 11:50:13.103196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46573d064bf4'
down_revision = 'f54a480ef00c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_ad_accounts', schema=None) as batch_op:
        batch_op.drop_index('facebook_ad_account_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_ad_accounts', schema=None) as batch_op:
        batch_op.create_index('facebook_ad_account_id', ['facebook_ad_account_id'], unique=True)

    # ### end Alembic commands ###
