"""Add splited field to Video model

Revision ID: 651b72bf44ad
Revises: 6305ad39cb4f
Create Date: 2025-01-13 11:29:51.450143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651b72bf44ad'
down_revision = '6305ad39cb4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_ad_account_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'facebook_ad_accounts', ['facebook_ad_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_campaign', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('facebook_ad_account_id')

    # ### end Alembic commands ###
