"""Add user id to stack post

Revision ID: 82911264abbc
Revises: 3fc3e95e3c88
Create Date: 2025-01-12 09:33:20.014421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82911264abbc'
down_revision = '3fc3e95e3c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stack_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stack_post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
