"""Add type_duration column to video_split

Revision ID: d2fd176cc311
Revises: 3ff324eab5a6
Create Date: 2025-01-05 21:26:59.620801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2fd176cc311'
down_revision = '3ff324eab5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_split', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('video_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'video', ['video_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_split', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('video_id')
        batch_op.drop_column('type_duration')

    # ### end Alembic commands ###
