"""Add splited field to Video model

Revision ID: f54a480ef00c
Revises: 
Create Date: 2025-01-19 14:52:13.593797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f54a480ef00c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_account_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('playlist_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'facebook_account', ['facebook_account_id'], ['id'])
        batch_op.drop_column('facebook_user_id')

    with op.batch_alter_table('stack_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_account_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('stack_post_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'facebook_account', ['facebook_account_id'], ['id'])
        batch_op.drop_column('facebook_user_id')

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_account_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('video_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'facebook_account', ['facebook_account_id'], ['id'])
        batch_op.drop_column('facebook_user_id')

    with op.batch_alter_table('video_split', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_account_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('video_split_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'facebook_account', ['facebook_account_id'], ['id'])
        batch_op.drop_column('facebook_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_split', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_user_id', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('video_split_ibfk_2', 'facebook_account', ['facebook_user_id'], ['facebook_user_id'], ondelete='CASCADE')
        batch_op.drop_column('facebook_account_id')

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_user_id', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('video_ibfk_2', 'facebook_account', ['facebook_user_id'], ['facebook_user_id'], ondelete='CASCADE')
        batch_op.drop_column('facebook_account_id')

    with op.batch_alter_table('stack_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_user_id', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('stack_post_ibfk_3', 'facebook_account', ['facebook_user_id'], ['facebook_user_id'], ondelete='CASCADE')
        batch_op.drop_column('facebook_account_id')

    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_user_id', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('playlist_ibfk_1', 'facebook_account', ['facebook_user_id'], ['facebook_user_id'], ondelete='CASCADE')
        batch_op.drop_column('facebook_account_id')

    # ### end Alembic commands ###
